name: SonarQube Analysis

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Run tests with coverage
        run: bundle exec rspec

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=glebtv_activeadmin-searchable_select
            -Dsonar.sources=lib,app
            -Dsonar.tests=spec
            -Dsonar.ruby.coverage.reportPaths=coverage/coverage.xml
            -Dsonar.exclusions=spec/**/*,vendor/**/*,coverage/**/*,tmp/**/*